### ISSUE TITLE
Drag and drop crashes the program

### ISSUE THREAD

**Issue by Botspot** [l-koehler/FF-converter#12]
```
pi@raspberrypi:~ $ ffconverter
Traceback (most recent call last):
  File "/usr/local/pipx/venvs/ffconverter/lib/python3.11/site-packages/ffconverter/ffconverter.py", line 502, in filesList_add_dragged
    if fnames:
       ^^^^^^
NameError: name 'fnames' is not defined
Aborted
```
Dragging anything from the file manager to the list of input files results in this error.

It should be easy to reproduce, but if you cannot get it to happen on your system, I am using the `pcmanfm` file manager on Raspberry Pi OS Bookworm. (wayland, wayfire window manager)

**Comment by l-koehler** [comment]
Fixed in 2.4.0, thanks!
