### ISSUE TITLE
Converting documents tab is missing?

### ISSUE THREAD

**Issue by Botspot** [l-koehler/FF-converter#2]
Just wanted to check if you removed functionality here. I recall the old ff-multi-converter having the ability to convert between different document formats. I think there was a dedicated tab for choosing a format.
This seems to be missing in your version when I add a PDF. 
![20240102_16h31m22s_grim](https://github.com/l-koehler/FF-converter/assets/54716352/d62cebf6-b1e6-49b7-b020-13ec4460272b)

**Comment by l-koehler** [comment]
I did not remove functionality, but I did not want to clutter everything with tabs.
You should be able to add the file and choose the needed output format in the dropdown menu in the "All Formats" tab.
I did that for documents and markdown because these don't have any settings that would make an extra tab for these conversions useful.

**Comment by Botspot** [comment]
That makes sense. My confusion came from expecting this to be able to convert PDF to other document formats like .DOCX or .ODT. On first glance, it looked like this fork was 'incorrectly' treating PDFs as image files.
![20240102_16h37m29s_grim](https://github.com/l-koehler/FF-converter/assets/54716352/b36e8f63-9f1b-4045-b9e2-98a75bd8ff89)
But now I see that .txt files are recognized as documents and the usual document conversion options are listed. I will assume that converting PDFs to other document formats was never supported.

**Comment by l-koehler** [comment]
I am confused about that too, I think unoconv can do pdf -> docx etc, but imagemagick for some reason also offers some document conversions.
Maybe magick cant convert every input format into every output format? I am trying to fix that now.

**Comment by l-koehler** [comment]
the program can convert to .odt and .doc, its just the conversions that use magick that do not work for some reason.
Maybe I should just group magicks text conversions separately from magicks other conversions (or remove them, i think they are all also possible with unoconv?)

**Comment by Botspot** [comment]
> the program can convert to .odt and .doc, its just the conversions that use magick that do not work for some reason. Maybe I should just group magicks text conversions separately from magicks other conversions (or remove them, i think they are all also possible with unoconv?)

Feel free to take your time to decide how to best proceed. Just let me know when thie is at a point where it is ready to receive our userbase. I'm planning to move all current users of FF Multi Converter to your fork.

**Comment by l-koehler** [comment]
At least it doesn't hang anymore trying invalid conversions.
The program now ignores imagemagicks TXT, PDF and BRAILLE modules, which were mostly redundant/unknown file formats anyways.
will re-enable output to pdf later, once i figured out how exactly imagemagick modules work.

**Comment by l-koehler** [comment]
closing, letting imagemagick read all files in the modules TXT, PDF and BRAILLE is not working and will sometimes freeze the program.
If a user is sure that this is something they need, they can do so by using the "Image Settings" tab.
re-enabled imagemagick writing to PDFs, but common conversions to PDF will be handled by unoconv anyways.
